
name: ML Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train model
      run: |
        python src/train.py
    
    - name: Run tests
      run: |
        python -m pytest src/test_model.py

    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model_*.pth
        retention-days: 5
